---
title: "4Maps"
format: html
editor: visual
---

```{r}
library("tidyverse")
library("terra")
library("maptiles")
```

```{r}
#city centroid
cities<-read.csv("allcities_latlon.csv")

#get coordinate for city
df<-cities |>
  filter(Address=="Houston, TX") |>
  select(lon, lat)

#convert coordinates into a point shapefile
x <- vect(df, geom=c("lon", "lat"), crs="+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs ")

#light rail centroid
Transit_Map_GEO <- vect("National_Transit_Map_Routes/National_Transit_Map_Routes.shp")

trans <- subset(Transit_Map_GEO, Transit_Map_GEO$route_long == "METRORAIL RED LINE")

char_lr<-aggregate(trans, dissolve=TRUE)

lr_project<-project(char_lr, "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs ")
lr_buffer<-terra::buffer(lr_project, width = 2000) #2km buffer around light rail

#get roads data
r<-vect("tl_2021_txharris_roads/tl_2021_48201_roads.shp")
r_project<-project(r, "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs ")
i<-subset(r_project, r_project$RTTYP=="I")
ic_buffer<-terra::buffer(i, width = 500)
c<-subset(r_project, r_project$RTTYP=="C")
m<-subset(r_project, r_project$RTTYP=="M")
o<-subset(r_project, r_project$RTTYP=="O")
s<-subset(r_project, r_project$RTTYP=="S")
sc_buffer<-terra::buffer(s, width = 500)


#crop s and i highways that are within 10 km of the light rail centroid
sint<-crop(sc_buffer, lr_buffer)
iint<-crop(ic_buffer, lr_buffer)
u<-aggregate(rbind(sint, iint), dissolve=TRUE)

#make a buffer around major roads but take out areas that overlap with the light rail
u_buffer<-terra::buffer(u, width = 1000)

#writeVector(u_buffer, "houston_lr_buff_new", overwrite=TRUE)
```

```{r}
bg <- get_tiles(ext(lr_buffer), provider = "Esri.WorldGrayCanvas")
plot(bg)
lines(lr_project, col="yellow", lwd = 3)
lines(u_buffer, col = "black", lwd = 3)
legend("top", 
       legend = c("Light Rail Line", "Substitute Road Buffer"),  
       col = c("yellow", "black"),    
       lwd = 2,
       bty = "n")
```

```{r}
#get coordinate for city
df<-cities |>
  filter(joint_address=="Phoenix-Mesa, AZ") |>
  select(lon, lat)

#convert coordinates into a point shapefile
x <- vect(df, geom=c("lon", "lat"), crs="+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs ")

Transit_Map_GEO <- vect("Valley_Metro_Light_Rail/LightRailLine.shp")

trans <- subset(Transit_Map_GEO, Transit_Map_GEO$SYMBOLOGY=="METRO")
char_lr<-aggregate(trans, dissolve=TRUE)
lr_project<-project(char_lr, "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs ")
lr_buffer<-terra::buffer(lr_project, width = 2000) #2km buffer around light rail

#get roads data
r<-vect("tl_2021_azmaricopa_roads/tl_2021_04013_roads.shp")
r_project<-project(r, "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs ")
i<-subset(r_project, r_project$RTTYP=="I")
ic_buffer<-terra::buffer(i, width = 500)
c<-subset(r_project, r_project$RTTYP=="C")
m<-subset(r_project, r_project$RTTYP=="M")
o<-subset(r_project, r_project$RTTYP=="O")
s<-subset(r_project, r_project$RTTYP=="S")
sc_buffer<-terra::buffer(s, width = 500)


#crop s and i highways that are within 10 km of the light rail centroid
sint<-crop(sc_buffer, lr_buffer)
iint<-crop(ic_buffer, lr_buffer)
u<-aggregate(rbind(sint, iint), dissolve=TRUE)

#make a buffer around major roads but take out areas that overlap with the light rail
u_buffer<-terra::buffer(u, width = 1000)

#writeVector(u_buffer, "phoenix_lr_buff_new", overwrite=TRUE)
```

```{r}

e<-ext(lr_buffer)
e2<-ext(-112.14, -112.14+.4, 33.35, 33.35+0.37)
bg <- get_tiles(ext(lr_buffer), provider = "Esri.WorldGrayCanvas")

png("Presentation/images/treated_az.png", 
    res=500, width=6, height=5, units="in")

plot(e2, alpha=0, main="Treated Area in Phoenix-Mesa, AZ")
plot(bg, add=TRUE)
lines(u_buffer, col = "black", lwd = 5, add=TRUE)
plot(i, col="#7f7f7f", lwd = 1, add=TRUE)
plot(s, col="#7f7f7f", lwd = 1, add=TRUE)
plot(lr_project, col="#e21833", lwd = 3, add=TRUE)
legend("top", 
       legend = c("Light Rail Line", "Highways", "Substitute Highway Buffers"),  
       col = c("#e21833", "#7f7f7f", "black"),    
       lwd = 2,
       bty = "n")
dev.off()
```

```{r}
#city centroid
cities<-read.csv("allcities_latlon.csv")

#get coordinate for city
df<-cities |>
  filter(Address=="Charlotte, NC") |>
  select(lon, lat)

#convert coordinates into a point shapefile
x <- vect(df, geom=c("lon", "lat"), crs="+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs ")

#light rail centroid
char_lr <- vect("G:/Shared drives/2024 FIRE Light Rail/DATA/LYNX_Blue_Line_Route")
char_lr<-aggregate(char_lr, dissolve=TRUE)
lr_project<-project(char_lr, "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs ")

lrc<-centroids(lr_project, inside=FALSE)
lrc_buff<-buffer(lrc, width = 15000)
lr_buffer<-terra::buffer(lr_project, width = 5000)
#writeVector(lr_buffer, "Charlotte Shapefiles/lr_1km_buff", overwrite=TRUE)

#get roads data
r<-vect("G:/Shared drives/2024 FIRE Light Rail/DATA/tl_2021_ncmecklenburg_roads")
r_project<-project(r, "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs ")
i<-subset(r_project, r_project$RTTYP=="I")
ic_buffer<-terra::buffer(i, width = 500)
c<-subset(r_project, r_project$RTTYP=="C")
m<-subset(r_project, r_project$RTTYP=="M")
o<-subset(r_project, r_project$RTTYP=="O")
s<-subset(r_project, r_project$RTTYP=="S")
oc_buffer<-terra::buffer(o, width = 500)

#crop s and i highways that are within 10 km of the light rail centroid
oint<-crop(oc_buffer, lr_buffer)
iint<-crop(ic_buffer, lr_buffer)
u<-aggregate(rbind(oint, iint), dissolve=TRUE)

#make a buffer around major roads but take out areas that overlap with the light rail
u_buffer<-terra::buffer(u, width = 1000)
```

```{r}
g <- get_tiles(ext(lrc_buff), provider = "Esri.WorldGrayCanvas")
plot(bg, main="Treated Area in Charlotte, NC")
lines(lr_project, col="yellow", lwd = 3)
lines(u_buffer, col = "black", lwd = 3)
legend("top", 
       legend = c("Light Rail Line", "Substitute Road Buffer"),  
       col = c("yellow", "black"),    
       lwd = 2,
       bty = "n")
```

```{r}
bg <- get_tiles(ext(lrc_buff), provider = "Esri.WorldGrayCanvas")

e<-ext(lr_buffer)
e2<-ext(-81, -81+0.4, 35.06, 35.06+0.37)

png(filename="Presentation/images/treated_nc.png", 
    res=500, width=6, height=5, units="in")

plot(e2, alpha=0, main="Treated Area in Charlotte, NC")
plot(bg, add=TRUE)
plot(lr_project, col="#e21833", lwd = 3, add=TRUE)
plot(i, col="#7f7f7f", lwd = 1, add=TRUE)
plot(o, col="#7f7f7f", lwd = 1, add=TRUE)
lines(u_buffer, col = "black", lwd = 5)

legend("top", 
       legend = c("Light Rail Line", "Highways", "Substitute Highway Buffers"),  
       col = c("#e21833", "#7f7f7f", "black"),    
       lwd = 2,
       bty = "n")

dev.off()
```

```{r}
#city centroid
cities<-read.csv("allcities_latlon.csv")

#get coordinate for city
df<-cities |>
  filter(Address=="Minneapolis-St. Paul, MN") |>
  select(lon, lat)

#convert coordinates into a point shapefile
x <- vect(df, geom=c("lon", "lat"), crs="+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs ")

#light rail centroid
Transit_Map_GEO <- vect("National_Transit_Map_Routes/National_Transit_Map_Routes.shp")
trans <- subset(
  Transit_Map_GEO, 
  Transit_Map_GEO$route_url == "https://www.metrotransit.org/route/blue" | 
    Transit_Map_GEO$route_url == "https://www.metrotransit.org/route/green")
char_lr<-aggregate(trans, dissolve=TRUE)
lr_project<-project(char_lr, "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs ")
lr_buffer<-terra::buffer(lr_project, width = 2000) #2km buffer around light rail

#get roads data
r<-vect("G:/Shared drives/2024 FIRE Light Rail/DATA/tl_2021_mnramsey_roads")
r_project<-project(r, "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs ")
i<-subset(r_project, r_project$RTTYP=="I")
ic_buffer<-terra::buffer(i, width = 500)
c<-subset(r_project, r_project$RTTYP=="C")
m<-subset(r_project, r_project$RTTYP=="M")
o<-subset(r_project, r_project$RTTYP=="O")
s<-subset(r_project, r_project$RTTYP=="S")
sc_buffer<-terra::buffer(s, width = 500)

r2<-vect("G:/Shared drives/2024 FIRE Light Rail/DATA/tl_2021_mnhennepin_roads")
r_project<-project(r2, "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs ")
i2<-subset(r_project, r_project$RTTYP=="I")
ic2_buffer<-terra::buffer(i2, width = 500)
c2<-subset(r_project, r_project$RTTYP=="C")
m2<-subset(r_project, r_project$RTTYP=="M")
o2<-subset(r_project, r_project$RTTYP=="O")
s2<-subset(r_project, r_project$RTTYP=="S")
sc2_buffer<-terra::buffer(s2, width = 500)

#crop s and i highways that are within 10 km of the light rail centroid
sint<-crop(sc_buffer, lr_buffer)
iint<-crop(ic_buffer, lr_buffer)
sint2<-crop(sc2_buffer, lr_buffer)
iint2<-crop(ic2_buffer, lr_buffer)
u<-aggregate(rbind(sint, iint, sint2, iint2), dissolve=TRUE)

#make a buffer around major roads but take out areas that overlap with the light rail
u_buffer<-terra::buffer(u, width = 1000)

```

```{r}
png(filename="maps/treat_twin_cities.png")
bg <- get_tiles(ext(lr_buffer), provider = "Esri.WorldGrayCanvas")
plot(bg, main="Treated Area in the Twin Cities, MN")
lines(lr_project, col="yellow", lwd = 3)
lines(u_buffer, col = "black", lwd = 3)
legend("top", 
       legend = c("Light Rail Line", "Substitute Road Buffer"),  
       col = c("yellow", "black"),    
       lwd = 2,
       bty = "n")
dev.off()
```
