---
title: "DiD Results"
format: html
editor: visual
---

```{r}
#| echo: false
#| message: false
#| warning: false
library(tidyverse)
```

```{r}
#| echo: false
#| message: false
#| warning: false

construction<-as.Date("2005-03-01")
expansion<-as.Date("2012-07-01")
open<-as.Date("2008-12-27")

#start dif-in-dif data analysis
df<-read.csv("daily roads/panel_updated.csv") |>
  filter(Address=="Winston-Salem, NC" | Address=="Greenville, SC" | 
           Address=="Columbia, SC" | Address=="Asheville, NC" |
           Address=="Fayetteville, NC" | 
           Address=="Charlotte, NC" |
           Address=="Durham, NC" |
           Address=="Phoenix-Mesa, AZ" | 
           Address=="Tucson, AZ" | Address=="El Paso, TX-NM") |>
  #remove unwanted years
  mutate(date=as.Date(date)) |>
  filter(date<construction | date>open) |> 
  filter(date<expansion) |>
  mutate(operating=ifelse(date>open,1,0)) |>
  mutate(treatcity=ifelse(Address=="Charlotte, NC" | 
                            Address=="Phoenix-Mesa, AZ",
                          1,0)) |>
  mutate(dow=weekdays(date)) |>
  mutate(dow_m=paste0(dow,"-",month)) |>
  mutate(dow_my=paste0(dow,"-",month,"-",year))  |>
  mutate(dow_a=paste0(dow,"-",Address))
```

```{r}
#| echo: false
#| message: false
#| warning: false
#run difference-in-differences
library("fixest")
library("kableExtra")

wcontrols<- "Swnet_tavg+Lwnet_tavg+Qle_tavg+Qh_tavg+Qg_tavg+Snowf_tavg+Rainf_tavg+Evap_tavg+Qs_tavg+Qsb_tavg+Qsm_tavg+SnowT_tavg+AvgSurfT_tavg+SWE_tavg+SnowDepth_tavg+SoilMoist_S_tavg+SoilMoist_RZ_tavg+SoilMoist_P_tavg+ECanop_tavg+TVeg_tavg+ESoil_tavg+CanopInt_tavg+EvapSnow_tavg+ACond_tavg+TWS_tavg+GWS_tavg+Wind_f_tavg+Rainf_f_tavg+Tair_f_tavg+Qair_f_tavg+Psurf_f_tavg+SWdown_f_tavg+LWdown_f_tavg"
```

```{r}
mfe<-"| dow_m + Address"
myfe<-"| dow_my + Address"
dafe<- "| dow_a + Address"
dafem<-"| dow_a + Address + month"
dafemy<-"| dow_a + Address + month + year"

f<-as.formula(paste("pm25 ~ operating:treatcity + operating + ", 
                    wcontrols, mfe))
m1 <- feols(f, cluster = "Address", data = df)

f<-as.formula(paste("pm25 ~ operating:treatcity + operating + ", wcontrols, dafe))
m2 <- feols(f, cluster = "Address", data = df)

f<-as.formula(paste("pm25 ~ operating:treatcity + operating + ", 
                    wcontrols, dafem))
m3 <- feols(f, cluster = "Address", data = df)

etable(m1, m2, m3,
       se = "cluster",
       cluster = "Address",
       keep = c("operating x treatcity", "operating"),
       order = c("operating x treatcity", "operating"),
       se.below = TRUE,
       digits = 2,
       file="Results/twocities_did.tex",
       replace=TRUE,
       title="DiD Results for Both Cities",
       fitstat=c('n', 'ar2'),
       digits.stats = 2,
       signif.code=c("***"=0.01, "**"=0.05, "*"=0.10))


```

Day of week heterogeneous treatment effects.

```{r}
#| echo: false
#| message: false
#| warning: false
f<-as.formula(paste("pm25 ~ operating:treatcity:dow + operating:dow + ", wcontrols, dafem))
m5 <- feols(f, cluster = "Address", data = df)

etable(m5, 
       se = "cluster",
       cluster = "Address",
       keep = c("operating"),
       order = c("operating"),
       se.below = FALSE,
       digits = 2,
       replace=TRUE,
       file="Results/two_cities_dow_did.tex",
       title="DiD Results for Both Cities",
       fitstat=c('n', 'ar2'),
       digits.stats = 2,
       signif.code=c("***"=0.01, "**"=0.05, "*"=0.10))
```

Do the same task for the Twin Cities, Phoenix-Mesa, and Houston.

Check policy documentation to see if there are possible confounders.

<https://docs.google.com/document/d/1nAZGmyn-9E6KLMhhuHBZk20owC7ycSaH_hM3Qj7JbVY/edit?tab=t.0>
