---
title: "Find PM2.5 levels from highways"
format: html
editor: visual
---

```{r}
library("tidyverse")
library("terra")
library("maptiles")
```

Make shapefile for Houston

```{r}
#city centroid
cities<-read.csv("allcities_latlon.csv")

#get coordinate for city
df<-cities |>
  filter(Address=="Houston, TX") |>
  select(lon, lat)

#convert coordinates into a point shapefile
x <- vect(df, geom=c("lon", "lat"), crs="+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs ")

#light raile route shapefile
Transit_Map_GEO <- vect("National_Transit_Map_Routes/National_Transit_Map_Routes.shp")

trans <- subset(Transit_Map_GEO, Transit_Map_GEO$route_long == "METRORAIL RED LINE")

char_lr<-aggregate(trans, dissolve=TRUE)

lr_project<-project(char_lr, "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs ")

#make 10 km buffer around light rail centroid
lrc<-centroids(lr_project, inside=FALSE)
lrc_buff<-buffer(lrc, width = 10000)

#make 1 km buffer around light rail route 
#lr_buffer<-terra::buffer(lr_project, width = 1000)
#writeVector(lr_buffer, "Houston Shapefiles/lr_1km_buff", overwrite=TRUE)
lr_buffer<-vect("Houston Shapefiles/lr_1km_buff")
  
#get roads data
r<-vect("tl_2021_txharris_roads/tl_2021_48201_roads.shp")
r_project<-project(r, "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs ")
i<-subset(r_project, r_project$RTTYP=="I")
c<-subset(r_project, r_project$RTTYP=="C")
m<-subset(r_project, r_project$RTTYP=="M")
o<-subset(r_project, r_project$RTTYP=="O")
s<-subset(r_project, r_project$RTTYP=="S")

#make plot of houston and light rail buffer
bg <- get_tiles(ext(lr_buffer)) #choose a number that will give a good picture of the light rail area
plot(bg)
lines(lr_project, col="blue")
lines(lr_buffer, col="black")
lines(lrc_buff, col="darkgreen")
lines(s, col="purple")
lines(i, col="red")

#crop s and i highways that are within 10 km of the light rail centroid
sint<-crop(s, lrc_buff)
iint<-crop(i, lrc_buff)
u<-aggregate(rbind(sint, iint), dissolve=TRUE)

#make a buffer around major roads but take out areas that overlap with the light rail
u_buffer<-terra::buffer(u, width = 1000)
plot(bg)
lines(u_buffer, col="purple")
lines(lr_project, col="blue")
#writeVector(u_buffer, "Houston Shapefiles/roads_1km_buff", overwrite=TRUE)

#make a buffer of highways that intersect with the light rail
sint<-crop(s, lr_buffer)
iint<-crop(i, lr_buffer)
u<-aggregate(rbind(sint, iint), dissolve=TRUE)

#Plot the buffers
u_buffer2<-terra::buffer(u, width = 1000)
plot(bg)
lines(u_buffer2, col="purple")
lines(lr_project, col="blue")

```

Make shapefile for Charlotte

```{r}
#get coordinate for city
df<-cities |>
  filter(Address=="Charlotte, NC") |>
  select(lon, lat)

#convert coordinates into a point shapefile
x <- vect(df, geom=c("lon", "lat"), crs="+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs ")

#light rail centroid
char_lr <- vect("LYNX_Blue_Line_Route/LYNX_Blue_Line_Route.shp")
char_lr<-aggregate(char_lr, dissolve=TRUE)
lr_project<-project(char_lr, "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs ")

lrc<-centroids(lr_project, inside=FALSE)
lrc_buff<-buffer(lrc, width = 15000)
lr_buffer<-terra::buffer(lr_project, width = 10000)
#writeVector(lr_buffer, "Charlotte Shapefiles/lr_1km_buff", overwrite=TRUE)
#lr_buffer<-vect("Charlotte Shapefiles/lr_1km_buff")

#get roads data
r<-vect("tl_2021_ncmecklenburg_roads/tl_2021_37119_roads.shp")
r_project<-project(r, "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs ")
i<-subset(r_project, r_project$RTTYP=="I")
c<-subset(r_project, r_project$RTTYP=="C")
m<-subset(r_project, r_project$RTTYP=="M")
o<-subset(r_project, r_project$RTTYP=="O")
s<-subset(r_project, r_project$RTTYP=="S")

#make plot of light rail buffer
bg <- get_tiles(ext(lrc_buff)) #choose a number that will give a good picture of the light rail area
plot(bg)
lines(lr_project, col="blue")
lines(lr_buffer, col="black")
lines(lrc_buff, col="darkgreen")
lines(i, col="purple")
lines(o, col="red")

#crop s and i highways that are within 10 km of the light rail centroid
oint<-crop(o, lrc_buff)
iint<-crop(i, lrc_buff)
u<-aggregate(rbind(oint, iint), dissolve=TRUE)

#make a buffer around major roads but take out areas that overlap with the light rail
u_buffer<-terra::buffer(u, width = 1000)
plot(bg)
lines(u_buffer, col="purple")
lines(lr_buffer, col="black")
lines(lr_project, col="blue")
#writeVector(u_buffer, "Charlotte Shapefiles/roads_1km_buff", overwrite=TRUE)

#make a buffer of highways that intersect with the light rail
sint<-crop(s, lr_buffer)
iint<-crop(i, lr_buffer)
u<-aggregate(rbind(sint, iint), dissolve=TRUE)

sint_df <- as.data.frame(sint)
iint_df <- as.data.frame((iint))

#Plot the buffers
u_buffer2<-terra::buffer(u, width = 1000)
plot(bg)
lines(u_buffer2, col="purple")
lines(lr_project, col="blue")

#Buffer part 2
#US21 I77 US29 are substitutes
#I:interstate U:US route S:state route
```

Make shapefile for Phoenix-Mesa, Arizona

```{r}
#get coordinate for city
df<-cities |>
  filter(joint_address=="Phoenix-Mesa, AZ") |>
  select(lon, lat)

#convert coordinates into a point shapefile
x <- vect(df, geom=c("lon", "lat"), crs="+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs ")

Transit_Map_GEO <- vect("Valley_Metro_Light_Rail/LightRailLine.shp")

trans <- subset(Transit_Map_GEO, Transit_Map_GEO$SYMBOLOGY=="METRO")
char_lr<-aggregate(trans, dissolve=TRUE)
lr_project<-project(char_lr, "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs ")
lrc<-centroids(lr_project)

lrc_buff<-buffer(lrc, width = 20000)

#lr_buffer<-terra::buffer(lr_project, width = 1000)

#bg <- get_tiles(ext(lrc_buff)) #choose a number that will give a good picture of the light rail area
#plot(bg)
#lines(lr_project, col="blue")
#lines(lr_buffer, col="black")
#lines(lrc_buff, col="darkgreen")
#writeVector(lr_buffer, "Phoenix Shapefiles/lr_1km_buff", overwrite=TRUE)
lr_buffer<-vect("Phoenix Shapefiles/lr_1km_buff")

#get roads data
r<-vect("tl_2021_azmaricopa_roads/tl_2021_04013_roads.shp")
r_project<-project(r, "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs ")
i<-subset(r_project, r_project$RTTYP=="I")
c<-subset(r_project, r_project$RTTYP=="C")
m<-subset(r_project, r_project$RTTYP=="M")
o<-subset(r_project, r_project$RTTYP=="O")
s<-subset(r_project, r_project$RTTYP=="S")

#make plot of light rail buffer
bg <- get_tiles(ext(lrc_buff)) #choose a number that will give a good picture of the light rail area
plot(bg)
lines(lr_project, col="blue")
lines(lr_buffer, col="black")
lines(lrc_buff, col="darkgreen")
lines(i, col="purple")
lines(s, col="red")

#crop s and i highways that are within 10 km of the light rail centroid
sint<-crop(s, lrc_buff)
iint<-crop(i, lrc_buff)
u<-aggregate(rbind(sint, iint), dissolve=TRUE)

#make a buffer around major roads but take out areas that overlap with the light rail
u_buffer<-terra::buffer(u, width = 1000)
plot(bg)
lines(u_buffer, col="purple")
lines(lr_project, col="blue")
lines(lr_buffer, col="black")
lines(lrc_buff, col="darkgreen")
#writeVector(u_buffer, "Phoenix Shapefiles/roads_1km_buff", overwrite=TRUE)

#make a buffer of highways that intersect with the light rail
sint<-crop(s, lr_buffer)
iint<-crop(i, lr_buffer)
u<-aggregate(rbind(sint, iint), dissolve=TRUE)

#Plot the buffers
u_buffer2<-terra::buffer(u, width = 1000)
plot(bg)
lines(u_buffer2, col="purple")
lines(lr_project, col="blue")
```

Make shapefile for Twin Cities, MN

```{r}
#get coordinate for city
df<-cities |>
  filter(Address=="Minneapolis-St. Paul, MN") |>
  select(lon, lat)

#convert coordinates into a point shapefile
x <- vect(df, geom=c("lon", "lat"), crs="+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs ")

Transit_Map_GEO <- vect("National_Transit_Map_Routes/National_Transit_Map_Routes.shp")
trans <- subset(
  Transit_Map_GEO, 
  Transit_Map_GEO$route_url == "https://www.metrotransit.org/route/blue" | 
    Transit_Map_GEO$route_url == "https://www.metrotransit.org/route/green")
char_lr<-aggregate(trans, dissolve=TRUE)
lr_project<-project(char_lr, "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs ")
lrc<-centroids(lr_project, inside=FALSE)
lrc_buff<-buffer(lrc, width = 10000)

#lr_buffer<-terra::buffer(lr_project, width = 1000)

#bg <- get_tiles(ext(lrc_buff)) #choose a number that will give a good picture of the light rail area
#plot(bg)
#lines(lr_project, col="blue")
#lines(lr_buffer, col="black")
#lines(lrc_buff, col="darkgreen")
#writeVector(lr_buffer, "Twin Cities Shapefiles/lr_1km_buff", overwrite=TRUE)
lr_buffer<-vect("Twin Cities Shapefiles/lr_1km_buff")

#get roads data
r<-vect("tl_2021_mnhennepin_roads/tl_2021_27053_roads.shp")
r_project<-project(r, "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs ")
i<-subset(r_project, r_project$RTTYP=="I")
c<-subset(r_project, r_project$RTTYP=="C")
m<-subset(r_project, r_project$RTTYP=="M")
o<-subset(r_project, r_project$RTTYP=="O")
s<-subset(r_project, r_project$RTTYP=="S")

#make plot of light rail buffer
bg <- get_tiles(ext(lrc_buff)) #choose a number that will give a good picture of the light rail area
plot(bg)
lines(lr_project, col="blue")
lines(lr_buffer, col="black")
lines(lrc_buff, col="darkgreen")
lines(i, col="purple")
lines(s, col="red")

#crop s and i highways that are within 10 km of the light rail centroid
sint<-crop(s, lrc_buff)
iint<-crop(i, lrc_buff)
u<-aggregate(rbind(sint, iint), dissolve=TRUE)

#make a buffer around major roads but take out areas that overlap with the light rail
u_buffer<-terra::buffer(u, width = 1000)
plot(bg)
lines(u_buffer, col="purple")
lines(lr_project, col="blue")
#writeVector(u_buffer, "Twin Cities Shapefiles/roads_1km_buff", overwrite=TRUE)

#make a buffer of highways that intersect with the light rail
sint<-crop(s, lr_buffer)
iint<-crop(i, lr_buffer)
u<-aggregate(rbind(sint, iint), dissolve=TRUE)

#Plot the buffers
u_buffer2<-terra::buffer(u, width = 1000)
plot(bg)
lines(u_buffer2, col="purple")
lines(lr_project, col="blue")
```

Combine all highway buffers into one shapefile

```{r}
m<-vect("Twin Cities Shapefiles/roads_1km_buff")
c<-vect("Charlotte Shapefiles/roads_1km_buff")
a<-vect("Phoenix Shapefiles/roads_1km_buff")
h<-vect("Houston Shapefiles/roads_1km_buff")
hb<-rbind(m, c, a, h)
```

```{r}
#get pm2.5 data for one month
path<-"G:/Shared drives/2023 FIRE-SA PRM/Spring Research/Light Rails/DATA/PM25/"
months<-dir(path)
# for each month
for (m in 1:length(months)) {
  print(months[m])
  #for (m in 1:2) {
  days<-dir(paste0(path,months[m]))
  
  # for each day in this month
  days_output<-c()
  for (d in 1:length(days)) {
    #for (d in 1:2) {
    
    print(days[d])
    r<-rast(paste0(path, months[m], "/", days[d]))
    raster_project <- terra::project(r,  "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs ")
    int<-crop(raster_project, hb,
          snap="in",
          mask=TRUE)
    
    cntrl_df<-terra::extract(int, hb, fun="mean", na.rm=TRUE)
    names(cntrl_df)<-c("city_num","pm25")
    output <- as.data.frame(c("date"=days[d], cntrl_df))
    days_output<-rbind(days_output, output)
    
  }
  write.csv(days_output, 
            paste0("PM25_daily/highway_buffers_",
                   months[m],
                   ".csv")
            , row.names = F)
}
```

Aggregate data into one data frame

```{r}
idv_cities<-rbind(cities[29,], cities[28,], cities[38,], cities[30,])

idv_cities$city_num <- seq.int(4)
```

```{r}
f<-dir("PM25_daily", pattern="highway")

p_highway<-c()
for (i in 1:length(f)) {
  print(f[i])
  pdf<-read.csv(paste0("PM25_daily/",f[i])) |>
    mutate(year=substr(date, 1, 4)) |>
    mutate(month=substr(date, 5, 6)) |>
    mutate(day=substr(date, 7,8))
  
  p_highway<-rbind(p_highway, pdf)
}
```

```{r}
ph<-merge(idv_cities, p_highway, by="city_num")

write.csv(ph, "pm25_highway_daily.csv", row.names=F)
```
