---
title: "Make time plots"
format: html
editor: visual
---

## Charlotte

PM2.5 around city centroid

```{r}
files<-dir("PM25_daily", pattern="lr_centroid")

pm_char<-c()
for (i in 1:length(files)) {
  df<-read.csv(paste0("PM25_daily/", files[i])) |>
    filter(city_num==1)
  pm_char<-rbind(pm_char, df)
}

pm_char2<-pm_char |>
  mutate(year=substr(date, 1, 4), month=substr(date, 5,6)) |>
  mutate(Date=as.Date(paste0(year, "-", month, "-01"))) |>
  group_by(Date) |>
  summarise(PM25=mean(pm25)) |>
  filter(Date<as.Date("2015-01-01"))
```

```{r}

png("Presentation/images/timetrend.png", 
    res=500, width=8, height=5, units="in")

ggplot(data=pm_char2, aes(y=PM25, x=Date)) + 
  geom_line(size=1) + 
  geom_vline(aes(xintercept=as.Date("2007-11-01"), col="LR Opening"), 
             linetype="dashed", size=2)+
  scale_colour_manual(values="#e21833")+
  annotate("rect", xmin = as.Date("2005-01-01"), xmax = as.Date("2007-11-01"), 
           ymin = 0, ymax = 25, alpha = .5,fill = "grey")+
  annotate("rect", xmin = as.Date("2012-12-01"), xmax = as.Date("2015-01-01"), 
           ymin = 0, ymax = 25, alpha = .5,fill = "grey")+
  annotate("text", x=as.Date("2006-06-01"), y=24, label= "Construction") +
  annotate("text", x=as.Date("2014-01-01"), y=24, label= "Expansion") +
  theme_bw() + 
  ylab("PM2.5 (in ug/m3)") + 
  xlab("Date") + 
  ggtitle("Average PM2.5 10 km around LYNX Metro's Light Rail")

dev.off()
```

```{r}
library("tidyverse")


pm<-read.csv("daily roads/panel_updated.csv")
cgroup<-c("Asheville, NC", "Charleston, SC", "Charlotte, NC",
          "Columbia, SC", "Durham, NC", "Fayetteville, NC", 
          "Greenville, SC", "Wilmington, NC",
          "Winston-Salem, NC")

pm_month<-pm |>
  group_by(Address, month, year) |>
  summarise(pm25=mean(pm25)) |>
  filter(Address %in% cgroup) |>
  mutate(date=as.Date(paste0(as.character(year),"-",
                             as.character(month),"-",
                             "01"), "%Y-%m-%d"))

pm_cntrl<-pm_month |>
  filter(Address!="Charlotte, NC")

pm_char<-pm_month |>
  filter(Address=="Charlotte, NC")


maxdate<-max(pm_month$date)

library(RColorBrewer)
g<-brewer.pal(10, "Greys")
pal<-c(g[1:2], "#e21833", g[3:7])
  
png("Presentation/images/nc_parallel.png", 
    res=500, width=6, height=6, units="in")

ggplot(data=pm_cntrl, aes(y=pm25, x=date, col=Address)) + 
  geom_line(size=1) + 
  scale_color_manual(values=pal)+
  annotate("rect", xmin = as.Date("2005-01-01"), xmax = as.Date("2007-11-01"), 
           ymin = 0, ymax = 25, alpha = .5,fill = "grey")+
  annotate("rect", xmin = as.Date("2012-12-01"), xmax = maxdate, 
           ymin = 0, ymax = 25, alpha = .5,fill = "grey")+
  theme_bw() + 
  ylab("PM2.5 (in ug/m3)") + 
  xlab("Date") + 
  ggtitle("PM2.5 in Charlotte its Control Cities") + 
  geom_line(data=pm_char, aes(y=pm25, x=date, col="Charlotte, NC"), size=0.7) 

dev.off()
```

## Phoenix

```{r}
library("tidyverse")


pm<-read.csv("daily roads/panel_updated.csv")
cgroup<-c("Phoenix-Mesa, AZ", "Tucson, AZ", "El Paso, TX-NM")

pm_month<-pm |>
  group_by(Address, month, year) |>
  summarise(pm25=mean(pm25)) |>
  filter(Address %in% cgroup) |>
  mutate(date=as.Date(paste0(as.character(year),"-",
                             as.character(month),"-",
                             "01"), "%Y-%m-%d"))

pm_cntrl<-pm_month |>
  filter(Address!="Phoenix-Mesa, AZ")

pm_char<-pm_month |>
  filter(Address=="Phoenix-Mesa, AZ")

maxdate<-max(pm_month$date)

library(RColorBrewer)
g<-brewer.pal(5, "Greys")
pal<-c(g[2],"#e21833", g[3])
  
png("Presentation/images/az_parallel.png", 
    res=500, width=6, height=6, units="in")

ggplot(data=pm_cntrl, aes(y=pm25, x=date, col=Address)) + 
  geom_line(size=1) + 
  scale_color_manual(values=pal)+
  annotate("rect", xmin = as.Date("2005-03-01"), xmax = as.Date("2007-11-01"), 
           ymin = 0, ymax = 25, alpha = .5,fill = "grey")+
  annotate("rect", xmin = as.Date("2012-07-01"), xmax = maxdate, 
           ymin = 0, ymax = 25, alpha = .5,fill = "grey")+
  theme_bw() + 
  ylab("PM2.5 (in ug/m3)") + 
  xlab("Date") + 
  ggtitle("PM2.5 in Phoenix-Mesa its Control Cities") + 
  geom_line(data=pm_char, aes(y=pm25, x=date, col="Phoenix-Mesa, AZ"), size=0.7) 

dev.off()
```

## Ridership

```{r}
library("tidyverse")

trans<-read.csv("ntd_by_year.csv") 

charlotte<-trans |>
  filter(Urbanized.Area=="Charlotte, NC" | Urbanized.Area=="Phoenix-Mesa, AZ") 

png("Presentation/images/ridership.png", 
    res=500, width=10, height=5, units="in")

ggplot(data=charlotte)+
  geom_line(aes(y=LR, x=year, col="Light Rail"), lwd=2)+
  geom_line(aes(y=bus, x=year, col="Bus"), lwd=2) + 
  geom_line(aes(y=cars, x=year, col="Taxi"), lwd=2) + 
  geom_line(aes(y=oth, x=year, col="Other"), lwd=2) + 
  ggtitle("Annual Number of Trips for Each Public Transport Mode")+
  xlab("Year") +
  ylab("Unlinked Passenger Trips")+
  geom_vline(xintercept=2007, linetype = "dotted", lwd=2)+
  theme_bw()+
  scale_color_manual(values=c("#ffd200", "#e21833", "#ad7231", "#454545"))+
  scale_x_continuous(breaks = seq(min(charlotte$year), 
                                  max(charlotte$year), by = 2))+
  facet_wrap(~Urbanized.Area)

dev.off()
```
