---
title: "Sythetic Control Notes"
author: "Thanicha"
format: html
editor: visual
---

-   The control group are untreated units.

-   The set of predictors $k$ for unit $j$ $X_{1j},...,X_{kj}$ included pre-intervention values of $Y_{jt}$ and which are unaffected by the intervention.

-   $\tau = Y_I - Y_N$ is the effect of the intervention

Bias bound

-   Linear factor model for the control variable $Y_{jt} ^N = \delta_t + \theta_t Z_j + \lambda _t \mu_j + \epsilon_{jt}$

    -   $Z_j$ are observed predictors (factor loadings)

    -   $\mu_j$ are unobserved predictors (factor loadings)

    -   A synthetic control that reproduces the values of $Z_1$ and $\mu_1$ would provide an unbiased estimator for the treatment effect of the treated.

    -   Overfitting bias - when $\mu_j$ is unobserved, small pre-intervention period, large variations in transitory shocks.

-   $X_1$ vector that includes $Z_1$ and pre-intervention outcomes from the treated unit

-   $X_0$ vector that includes $Z_0$ and pre-intervention outcomes from untreated unit.

-   $X_1 = X_0 W*$ is the synthetic control that can represent the treated unit.
